<div class='col-sm-12'>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Om Angular</a>
      </div>
    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a class='ang_home' href="#home">Home</a></li>
          <li><a class='ang_profile' href="#profile">Profile</a></li>
          <li><a class='ang_gallary' href="#gallary">User's Details</a></li> 
          <li><a class='ang_clips' href="#clips">Coupons</a></li>
          <li><a class='ang_mp3' href="#mp3">Shop</a></li>
          <li><a class='ang_shops' href="#shops">Manage User</a></li>
          <li><a class='ang_admin' href="#admin">Admin</a></li>
          <li><a class='ang_cart' href='#cart'>Cart</a></li>
          <li><a class='ang_contact' href='#contact'>Contact Us</a></li>
        </ul>
     <!--  <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form> -->
    </div>
    </div>
  </nav>
      </div>